const BOT = require('./vk')
const Games = require('./commands/games')
const Kicker = require('./commands/kicker')
const SavedData = require('./commands/savedData')
const dateCommand = require('./commands/date')
const Citgen = require('./commands/citgen')
const Troll = require('./commands/troll')
const Autosend = require('./automaticSender')
const Start = require("./commands/start")
const Help = require("./commands/help")
const Commands = require("./commands/commands")
const Trollgen = require('./commands/trollgen')
const Feedback = require("./commands/feedback")

Start.run()
Help.run()
Commands.run()
Feedback.run()
Kicker.run()
Citgen.run()
dateCommand.run()
SavedData.run()
Games.run()
Troll.run
Autosend.run()
Trollgen.run()

BOT.VK.updates.start().catch(err => console.error(err))
