export enum CommandsEnum {
    BALL_GAME = 'BALL_GAME',

    GET_MONDAY = 'GET_MONDAY',
    GET_TUESDAY = 'GET_TUESDAY',
    GET_WEDNESDAY = 'GET_WEDNESDAY',
    GET_THURSDAY = 'GET_THURSDAY',
    GET_FRIDAY = 'GET_FRIDAY',
    GET_SATURDAY = 'GET_SATURDAY',

    SET_MONDAY = 'SET_MONDAY',
    SET_TUESDAY = 'SET_TUESDAY',
    SET_WEDNESDAY = 'SET_WEDNESDAY',
    SET_THURSDAY = 'SET_THURSDAY',
    SET_FRIDAY = 'SET_FRIDAY',
    SET_SATURDAY = 'SET_SATURDAY',

    CLOSE_KEYBOARD = 'CLOSE_KEYBOARD',
}
